name: main
sha1: d11336b31aeceec48267062676e9c3f0833ec13f
options:
  basename: main
  target_path: disks/jp/SLPS_017.97
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp/main
  src_path: src/main
  asset_path: build/jp/psx/generated/assets/main
  build_path: build

  ld_script_path: build/jp/psx/generated/main.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80144E0C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp/symbols.txt
    - config/jp/symbols_main.txt

  undefined_funcs_auto_path: build/jp/psx/generated/undefined_funcs_auto_main.txt
  undefined_syms_auto_path: build/jp/psx/generated/undefined_syms_auto_main.txt

  ld_gp_expression: main_SDATA_START + 0x8000

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  migrate_rodata_to_functions: False

  create_data_pads: False

  use_gp_rel_macro: True

segments:
  - name: header
    type: data
    start: 0x0
    vram: 0x80090000
    align: 4
    subalign: 4

  - name: main
    type: code
    start: 0x800
    vram: 0x80090800
    align: 4
    subalign: 4
    subsegments:
      - [0x800, asm, main]
      - [0x13FB4, c, world_object]
      - [0x1443C, c, file]
      - [0x14A74, c, math]
      - [0x14DF8, asm]
      - [0x16048, c, _psstart]
      - [0x16190, asm]
      - [0x203C8, c, fade]
      - [0x208B4, c, aabb]
      - [0x20E40, c, efe]
      - [0x242CC, asm]
      - [0x34B98, c, overworld_evochart_view]
      - [0x35208, asm]
      - [0x3696C, c, overworld_moves_text]
      - [0x36CC0, asm]
      - [0x381B4, c, overworld_playerinfo_text]
      - [0x38390, c, overworld_evochart_text]
      - [0x384D8, c, overworld_medal_text]
      - [0x386A4, c, overworld_card_text]
      - [0x38758, c, map_collision]
      - [0x39084, c, particle]
      - [0x39950, asm]
      - [0x707DC, c, file_queue]
      - [0x70ECC, asm]
      - [0x729B4, c, fish]
      - [0x72DFC, asm]
      - [0x75268, c, tournament]
      - [0x7587C, c, evl]
      - [0x75B80, asm]
      - [0x78514, c, kar]
      - [0x7855C, c, efe_table]
      - [0x78668, asm]
      - [0x799BC, c, butterfly]
      - [0x79D94, asm]
      - [0x842D8, c, bubble]
      - [0x84F04, asm]
      - [0x89E64, rodata, main]
      - [0x8A700, .rodata, efe]
      - [0x8A71C, rodata]
      - [0x8ACF0, .rodata, overworld_evochart_view]
      - [0x8AD04, .rodata, overworld_moves_text]
      - [0x8AD1C, .rodata, overworld_playerinfo_text]
      - [0x8AD34, .rodata, overworld_medal_text]
      - [0x8AD50, rodata]
      - [0x8B9CC, data, main]
      - [0x9EB5C, .data, toilet_data]
      - [0x9EBAC, .data, door_mapdata]
      - [0x9F0BC, .data, efe]
      - [0x9F198, data]
      - [0xA8A38, .data, efe_table]
      - [0xA8A78, data]
      - [0xA9A44, .data, butterfly]
      - [0xA9A68, data]
      - [0xAA5FC, .data, bubble]
      - [0xAA8D4, data]
      - [0xACE0C, sdata, main]
      - [0xAD4E0, .sdata, efe]
      - [0xAD4F0, sdata]
      - [0xAD7C4, .sdata, file_queue]
      - [0xAD7C8, sdata]
      - [0xAD7D4, .sdata, efe_table]
      - [0xAD7D8, sdata]
      - [0xAD870, .sdata, bubble]
      - [0xAD8E4, sdata]
      - [0xAD938, .sdata, btl/command_shout]
      - [0xAD94C, sdata]

  - [0xADF1C]
