name: murd
sha1: b684a4b33218915fe3de3d3bf22debff52bd16ed
options:
  basename: murd
  target_path: disks/jp/MURD_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp/murd
  src_path: src/murd
  asset_path: build/jp/psx/generated/assets/murd
  build_path: build

  ld_script_path: build/jp/psx/generated/murd.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80144E0C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp/symbols.txt

  undefined_funcs_auto_path: build/jp/psx/generated/undefined_funcs_auto_murd.txt
  undefined_syms_auto_path: build/jp/psx/generated/undefined_syms_auto_murd.txt

  use_gp_rel_macro: True

segments:
  - name: murd
    type: databin
    start: 0x0
    vram: 0x8007C000

  - [0x33D8]
