name: shop
sha1: 12abe8e6590b49a4a32a96e4b47441a3fa7a7073
options:
  basename: shop
  target_path: disks/jp/SHOP_REL.BIN
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/jp/shop
  src_path: src/shop
  asset_path: build/jp/psx/generated/assets/shop
  build_path: build

  ld_script_path: build/jp/psx/generated/shop.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  gp_value: 0x80144E0C

  generate_asm_macros_files: False

  section_order: [".text", ".rodata", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/jp/symbols.txt

  undefined_funcs_auto_path: build/jp/psx/generated/undefined_funcs_auto_shop.txt
  undefined_syms_auto_path: build/jp/psx/generated/undefined_syms_auto_shop.txt

  use_gp_rel_macro: True

segments:
  - name: shop
    type: databin
    start: 0x0
    vram: 0x80080800

  - [0x7E10]
